version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/docker/docker-credential-helpers/credentials.Name={{.ProjectName}}"
      - "-X github.com/docker/docker-credential-helpers/credentials.Version={{.Version}}"
      - "-X github.com/docker/docker-credential-helpers/credentials.Revision={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: docker-credential-env
archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: isometry
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    description: Environment-driven Docker credential helper
    homepage: https://just.breathe.io/project/docker-credential-env/
    test: |
      system "#{bin}/docker-credential-env --version"
    install: |
      bin.install "docker-credential-env"
