---
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: sast
        name: sast
        entry: gosec ./...
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: go-test
        name: go-test
        entry: go test -v ./...
        language: system
        pass_filenames: false
